FROM public.ecr.aws/lambda/python:3.11

COPY models/all-mpnet-base-v2 ${LAMBDA_TASK_ROOT}/models/all-mpnet-base-v2/

COPY requirements.lambda.txt ${LAMBDA_TASK_ROOT}/requirements.txt
RUN pip install -r ${LAMBDA_TASK_ROOT}/requirements.txt

COPY src ${LAMBDA_TASK_ROOT}/src
COPY lambda_function.py ${LAMBDA_TASK_ROOT}/lambda_function.py

CMD [ "lambda_function.lambda_handler" ]
